### ISSUE TITLE
Unclear what the styles.css is for?

### ISSUE THREAD

**Issue by advename** [wikiti/pandoc-book-template#11]
First of all - THANK YOU for this awesome package! I've been trying to convert md to pdf in a pretty way and failed miserably because Pandoc simply works better going the latex way than html.

---
Now, you have the styles.css file in the project, but css is only supported via html. What is the purpose of this file then? Or how would you use it?

**Comment by wikiti** [comment]
Hi @advename 

> First of all - THANK YOU for this awesome package! I've been trying to convert md to pdf in a pretty way and failed miserably because Pandoc simply works better going the latex way than html.

You're welcome!

> Now, you have the styles.css file in the project, but css is only supported via html. What is the purpose of this file then? Or how would you use it?

That's a good question. I've been looking around, and looks like it's not supported on PDF (Latex based) nor DOCX files. On this template, it could only be used on EPUB and HTML formats right now.

I think this may be addressed in two different ways:

- Stop using PDF's Xelatex engine, and start using html2pdf to convert it automatically to PDF/DOCX (supported by Pandoc). Unfortunately, this won't work for DOCX files.
- Update this template to include a new folder, templates, to include format-independant styles or templates. It could include some basic/pretty templates.

What do you think about the second one?

**Comment by advename** [comment]
Yes, that's what i also thought. I really wish to use CSS in my final product, but the Latex conversion is much better IMHO.

I think Ill have to use the HTML approach, thanks again tho!

**Comment by wikiti** [comment]
I've already implemented templates support, so I'm closing this issue. Please, feel free to comment in this one o create a new one in case something is not working properly.
