### ISSUE TITLE
A word of thanks

### ISSUE THREAD

**Issue by aahnik** [wikiti/pandoc-book-template#14]
Thanks a lot, @wikiti @mofosyne @ilikerobots, for this template and make file automation.

I was struggling for hours to use pandoc commands correctly, and how to organize everything. The official tutorial https://pandoc.org/epub.html was not that helpful. They were typing some long commands. 

I was looking for organizing all chapters in a folder, with the filename as chapter name. I was unable to find a proper tutorial on the internet.

This template and the makefile really made it ultra-easy for me to do the job. It saved me a lot of time.
I was looking for something **just like this**

### Thanks a lot to all who created this.

>GitHub has not yet rolled out discussions, so I am using the issues.
Please close this issue after you read it.

**Comment by wikiti** [comment]
You are very welcome, @aahnik !

Please, if you have any more questions, suggestions or have found any bug, feel free to open a new issue.

Best regards,
Daniel
