### ISSUE TITLE
[bug] "template" (line 11, column 1): unexpected "s" expecting "$endif$"

### ISSUE THREAD

**Issue by aahnik** [wikiti/pandoc-book-template#16]
Error in building epub.

```
❯ make epub
mkdir -p build/epub
awk 'FNR==1 && NR!=1 {print "\n\n"}{print}' chapters/*.md | tee  | pandoc --toc --toc-depth 2 --webtex --metadata-file metadata.yml   --template templates/epub.html --epub-cover-image images/cover.png -o build/epub/book.epub
"template" (line 11, column 1):
unexpected "s"
expecting "$endif$"
make: *** [Makefile:78: build/epub/book.epub] Error 5
```

See this gif: I just cloned the repo and ran `make epub`, which was earlier working perfectly fine.

![pandoc_tem](https://user-images.githubusercontent.com/66209958/96368837-fee0f900-1173-11eb-9391-4355b9b9f2a1.gif)

**Comment by wikiti** [comment]
Hi @aahnik !

Could you please make sure that you have the latest pandoc version?

**Comment by aahnik** [comment]
yes, i cloned the latest version

**Comment by wikiti** [comment]
@aahnik Could you please tell me which version are you using?

**Comment by aahnik** [comment]
i cloned it from master branch just now

**Comment by aahnik** [comment]
i see no releases in this repo.
I believe the master branch is the final production branch,

**Comment by wikiti** [comment]
@aahnik I'm talking about pandoc, not this repository. Please run `pandoc --version`, and see if you're using the latest.

**Comment by aahnik** [comment]
```
❯ pip show pandoc
Name: pandoc
Version: 2.0a5
Summary: Pandoc Documents for Python
Home-page: UNKNOWN
Author: Sébastien Boisgérault
Author-email: Sebastien.Boisgerault@mines-paristech.fr
License: MIT License
Location: /home/aahnik/.local/lib/python3.8/site-packages
Requires: ply, plumbum
Required-by: 
```

**Comment by aahnik** [comment]
thanks @wikiti  for asking the version question
Issue solved after upgrading to the latest version of pandoc.
