### ISSUE TITLE
Page break after table of contents?

### ISSUE THREAD

**Issue by alexispurslane** [wikiti/pandoc-book-template#17]
I would like to start a new page after the table of contents, in order to format this more like a real book. I tried to edit the template to add a `\newpage` or `\pagebreak` but that didn't work. Is there a way to do this?

**Comment by wikiti** [comment]
Hi @christopherdumas,

I'm assuming you're exporting to PDF (latex). You may want to modify the template file, located at `templates/pdf.latex`. I've make a simple change, and it seems page breaks are working properly:

````diff
diff --git a/templates/pdf.latex b/templates/pdf.latex
index 4ceca43..442192f 100644
--- a/templates/pdf.latex
+++ b/templates/pdf.latex
@@ -409,6 +409,7 @@ $if(beamer)$
 \frame{\titlepage}
 $else$
 \maketitle
+\newpage
 $endif$
 $if(abstract)$
 \begin{abstract}
````

**Comment by wikiti** [comment]
Hello @christopherdumas,

Without your response, I assume that the issue is solved. Please feel free to comment on this same issue, or create a new one.
