### ISSUE TITLE
make html got error 5 in "template" (line 18, column 17)

### ISSUE THREAD

**Issue by TheListCamp** [wikiti/pandoc-book-template#18]
I downloaded the code of this repository and installed packages on ubuntu (Windows Sub System), when I run make html, I got the error message below:

> mkdir -p build/html
awk 'FNR==1 && NR!=1 {print "\n\n"}{print}' chapters/*.md | tee  | pandoc --toc --toc-depth 2 --webtex --metadata-file metadata.yml   --template templates/html.html --standalone --to html5 -o build/html/book.html
"template" (line 18, column 17):
unexpected "("
expecting "." or "$"
make: *** [Makefile:83: build/html/book.html] Error 5

**Comment by wikiti** [comment]
Hello @TheListCamp ,

Could you please provide more information? i.e. versions of `make`, `pandoc`, etc

Could you also please try to run the given commands on a linux cmd? Try running the piped commands on a sequential order and see which one failes, like so:

````
awk 'FNR==1 && NR!=1 {print "\n\n"}{print}' chapters/*.md

awk 'FNR==1 && NR!=1 {print "\n\n"}{print}' chapters/*.md | tee

awk 'FNR==1 && NR!=1 {print "\n\n"}{print}' chapters/*.md | tee | pandoc --toc --toc-depth 2 --webtex --metadata-file metadata.yml --template templates/html.html --standalone --to html5 -o build/html/book.html
````

**Comment by wikiti** [comment]
Hello @TheListCamp ,

Without a response, I'm assuming that the issue is solved. Please feel free to comment or open a new issue in case it is not yet solved.

**Comment by rogerkohlerjr** [comment]
I received the same error.  I commands you asked for and it had no problem with the awk or tee commands.  It fails on the pandoc command with error 5.

I'm running focal (Ubuntu 20.04 LTS on dual processor with 4GB memory) and my pandoc version is 2.5, make is version 4.2.1 and XeTeX 3.14159265-2.6-0.999991.

**Comment by wikiti** [comment]
> I received the same error. I commands you asked for and it had no problem with the awk or tee commands. It fails on the pandoc command with error 5.
> 
> I'm running focal (Ubuntu 20.04 LTS on dual processor with 4GB memory) and my pandoc version is 2.5, make is version 4.2.1 and XeTeX 3.14159265-2.6-0.999991.

You might want to try a newer version of pandoc, since the latest one is 3.6.3, and you are using 2.5 😅
