### ISSUE TITLE
Broken PDF export on macOS

### ISSUE THREAD

**Issue by xor-gate** [wikiti/pandoc-book-template#22]
**Environment**

```
macOS with homebrew
==> texlive: stable 20220321 (bottled), HEAD
XeTeX 3.141592653-2.6-0.999994 (TeX Live 2022/Homebrew)
==> pandoc: stable 2.19.2 (bottled), HEAD
```

**Problem**

```
jerry@jerrys-MacBook-Pro pandoc-book-template % make pdf
mkdir -p build/pdf
awk 'FNR==1 && NR!=1 {print "\n\n"}{print}' chapters/*.md | tee  | pandoc --toc --toc-depth 2 --webtex --metadata-file metadata.yml   --template templates/pdf.latex --pdf-engine xelatex -o build/pdf/book.pdf
Error producing PDF.
! Argument of \str_uppercase:n has an extra }.
<inserted text>
                \par
l.114   \setmainlanguage[]{}

make: *** [build/pdf/book.pdf] Error 43
```

I'm unable to get the offending .tex intermediate file because it is piped directly to pandoc. It is possible pandoc is to new and has a bug.

**Comment by wikiti** [comment]
Hey @xor-gate !

Tried with those latest versions in linux, and I get the very same error. I'll try to investigate it and see what I can find once I have some free time.

**Comment by wikiti** [comment]
Tied [this latex template](https://www.overleaf.com/latex/templates/basic-template/wswqstsqbzbz) without throwing any errors. Might be related to the `templates/pdf.latex` template 🤔

**Comment by xor-gate** [comment]
Yeah I had not much time to dive into it very deep. But its good you can reproduce the error.

**Comment by xor-gate** [comment]
I tried the "eisvogel.tex" pandoc latex template and it worked without problems. I'm not happy with the layout but it compiles.

https://github.com/Wandmalfarbe/pandoc-latex-template/blob/master/eisvogel.tex

**Comment by xor-gate** [comment]
I think I have found something intressting:

https://github.com/wikiti/pandoc-book-template/blob/d00921d1316b85d3e02eacc7e55406c2a4cd082d/templates/pdf.latex#L329-L331

When I run the pdf export using .tex output intermediate file the `\setmainlanguage` command has no parameters. This must be the problem. I tried to edit the metadata.yml and add the lang properties which did not work.

```latex
 51 \ifxetex
 52   % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
 53   \usepackage{polyglossia}
 54   \setmainlanguage[]{}
 55 \else
 56   \usepackage[shorthands=off,main=american]{babel}
 57 \fi
```

By following https://github.com/jgm/pandoc/issues/2174 I changed the pdf.latex code to:

```latex
328 \ifxetex
329   % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
330   \usepackage{polyglossia}
331   \setmainlanguage[$polyglossia-lang.options$]{$mainlang$}
332 $for(polyglossia-otherlangs)$
333   \setotherlanguage[$polyglossia-otherlangs.options$]{$otherlang$}
334 $endfor$
335 \else
```

Note the `mainlang` and `otherlang` pandoc template variables. Then I added to the metadata.yml the values `english` and it compiled without a sweat.

See commit:
* <https://github.com/wikiti/pandoc-book-template/commit/4536f1330a553c489e0056231ab906a683a96654#diff-db241a40cf9cbe22d674a20197e3f53594bb287012c504768bc17c2abf5b0935>
* https://github.com/wikiti/pandoc-book-template/commit/4536f1330a553c489e0056231ab906a683a96654#diff-c367683786fd98a0bdc160c6dcd37f8d75c0bbaf359290b15cf32759afbbe504

Its an easy fix, or you should update the metadata.yml to reflect the correct depth of the `polyglossia-lang.name` etc properties.

**Comment by wikiti** [comment]
That's great @xor-gate !

Thank you so much for taking the time to find a fix! I'll create a commit on the master branch and upload it ASAP.
