### ISSUE TITLE
Cover page for PDFs

### ISSUE THREAD

**Issue by flavienbwk** [wikiti/pandoc-book-template#23]
Hi,

I have a PNG image I want to set as the cover of my document. How can I achieve that with the provided latex file ?

Thank you.

**Comment by wikiti** [comment]
Hey @flavienbwk,

You might want to edit the `templates/pdf.latex` file to do so. I'm not a latex expert and I can't provide support for you on that aspect, but you may want to try [this StackOverflow solution](https://tex.stackexchange.com/questions/13912/how-to-insert-an-image-in-the-front-cover-of-a-report).

Best,
Daniel
