### ISSUE TITLE
pandoc-book-template license

### ISSUE THREAD

**Issue by ferranmesas** [wikiti/pandoc-book-template#4]
Hello! I was wondering what license is in use for the code itself. I see the default template references a CC license as an example, but I couldn't find one for the Makefile scripts.

Many thanks!

**Comment by wikiti** [comment]
Hey @ferranmesas !

Thank you for your note.

I have added a [LICENSE.md](https://github.com/wikiti/pandoc-book-template/blob/master/LICENSE.md) file with the MIT License, which I use in almost all my projects.

Best regards,
Daniel

**Comment by ferranmesas** [comment]
Thanks for the quick response!
