### ISSUE TITLE
Skipping Some Files

### ISSUE THREAD

**Issue by ghost** [wikiti/pandoc-book-template#5]
Is there a reason that this script would skip a few of my chapter files? I'm not sure why. I made sure they all use conforming file names and the # Titles are done properly. Perhaps it is something with Pandoc itself?

**Comment by wikiti** [comment]
Hi @poetgrant!

Thank you for using this template.

Could you please share your file directory tree, or provide a simple guide on how to replicate the problem?

Best regards,
Daniel

**Comment by ghost** [comment]
When I get back to my computer I can share my directory tree. Until then I'll explain.

When I run 'make' it does its thing and the output epub is missing 2 of the chapters. So I ran make with debugging and it doesn't actually look like it's skipping any of the files. If there were a way to get a more verbose output I might be able to figure it out.

After I posted this issue, I tried running pandoc without the Makefile and it still skipped some of the files in the epub build.

Would there be a reason that you know that pandoc is only including 11 of the 13 files in the epub?

**Comment by wikiti** [comment]
Hi again, @poetgrant 

> Would there be a reason that you know that pandoc is only including 11 of the 13 files in the epub?

I would need to know the file directory tree and the file contents to see why pandoc is skipping your files.

**Comment by ghost** [comment]
Okay, here it is.
![Screenshot from 2019-06-13 07-02-27](https://user-images.githubusercontent.com/43929985/59427807-83b24a80-8da9-11e9-8915-7e563b090b09.png)

**Comment by wikiti** [comment]
@poetgrant Which files are being skipped?

**Comment by ghost** [comment]
03 and 04 are being skipped and it builds into this:

![Screenshot from 2019-06-13 09-19-20](https://user-images.githubusercontent.com/43929985/59435805-6b97f680-8dbc-11e9-94ee-416bd2448b74.png)

**Comment by wikiti** [comment]
@poetgrant 

What about the contents of those files? Do they have something unsual, like garbage non-printable characters at the beginning of the file, or invalid markdown syntax?

Could you share them or a portion of them, to see if I can replicate and locate the error?

Does this problem also happen when exporting to other formats, like html or pdf?

**Comment by ghost** [comment]
Oh! Let me try exporting to PDF and HTML... I don't know why I didn't try that. I'll also zip the files and send it to you. Thank you. Give me a minute. 

Oh and thank you for your quick responses!

**Comment by ghost** [comment]
I sent an email to the one listed on your profile.

HTML and PDF skip those files too. There are some special UTF-8 characters, but they are in almost all of the files. They render fine in the other chapters.

(BTW, now you have a special advanced super rough draft of the book I am writing. hehehe)

**Comment by wikiti** [comment]
Hi @poetgrant,

Those files were actually included on your build, but not as titles, and therefore, not on the index.

If you search for `# The Troll` title, you'll see that it's on the same line as the last paragraph of the previous chapter.

Your `chapters/02-The-Fari-Snake.md` and `chapters/03-The-Troll.md` files do **not** have ending newlines.

Here's a better explanation on this problem: https://github.com/jgm/pandoc/issues/2494#issuecomment-153431356

After adding newlines at the end to those files, the problem seems solved.

Since this is not related to this repository, I'll close this issue.

Feel free to ask more questions!

> (BTW, now you have a special advanced super rough draft of the book I am writing. hehehe)

Fear not, ~~I've already posted it on Wattpad~~ I won't read, and it has been already remove from my desktop 😄

**Comment by ghost** [comment]
Omg! I can't believe it was something that simple.... Thank you! I'm 
sorry for my silliness. Consider the advance of my first 13 chapters as 
payment? :D Thank you again for everything! You have solved an issue 
that has been bugging me for over a week.
