### ISSUE TITLE
Make error: `Makefile:22: *** missing separator.  Stop.`

### ISSUE THREAD

**Issue by Gnosnay** [wikiti/pandoc-book-template#6]
Hi, I found one error when i run `make epub` without changing any file. i have no idea about that. could u please give me some advice?
### what i did
```
sudo apt-get install pandoc
sudo apt-get install make
sudo apt-get install texlive-latex-base texlive-latex-recommended   texlive-latex-extra texlive-fonts-recommended
git clone https://github.com/wikiti/pandoc-book-template.git
cd pandoc-book-template/
make epub
```

and then i get the messages as follows:
```
Makefile:22: *** missing separator.  Stop.
```

**Comment by wikiti** [comment]
Hello @Yansongsongsong ! 

Thank you for your report.

Looks like I broke TAB characters on the Makefile on [this previous commit](https://github.com/wikiti/pandoc-book-template/commit/6dc0a7b6a3f577d361e4f3bd365f1c864b0f2478).

It should be now fixed on the ``master`` branch.


Best regards,
Daniel
